#spring:
#  application:
#    name: user-service
#
#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      uri: http://localhost:8888/

resilience4j:
  retry:
    instances:
      basic:
        maxRetryAttempts: 3
        waitDuration: 8s
  ratelimiter:
    instances:
      multiRate:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 2s